"""Constants for XiaoDu Smart Home integration."""

DOMAIN = "xiaodu"

CONF_BDUSS = "bduss"

XIAODU_HOST = "https://xiaodu.baidu.com"

# Polling
POLL_INTERVAL = 30  # seconds

# Appliance types
TYPE_LIGHT = "LIGHT"
TYPE_SWITCH = "SWITCH"
TYPE_OUTLET = "SOCKET"
TYPE_HEATER = "HEATER"
TYPE_WASHING_MACHINE = "WASHING_MACHINE"
TYPE_WINDOW_OPENER = "WINDOW_OPENER"
TYPE_CLOTHES_RACK = "CLOTHES_RACK"
TYPE_AIR_FRESHER = "AIR_FRESHER"
TYPE_CURTAIN = "CURTAIN"
TYPE_AC = "AIR_CONDITION"
TYPE_DOOR_LOCK = "DOOR_LOCK"

# Groupings
SWITCH_TYPES = {
    TYPE_SWITCH, TYPE_OUTLET, TYPE_HEATER, TYPE_WASHING_MACHINE,
    TYPE_WINDOW_OPENER, TYPE_CLOTHES_RACK, TYPE_AIR_FRESHER,
}
LIGHT_TYPES = {TYPE_LIGHT}
COVER_TYPES = {TYPE_CURTAIN}
CLIMATE_TYPES = {TYPE_AC}
LOCK_TYPES = {TYPE_DOOR_LOCK}
